# Generated by Django 4.2.6 on 2023-12-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
    ]
