# Generated by Django 4.0.6 on 2023-12-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency_rates', '0001_initial'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditconfiguration',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='currency_rates.currency'),
        ),
        migrations.AddField(
            model_name='credit',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_configuration', to='credit.creditconfiguration'),
        ),
        migrations.AddField(
            model_name='credit',
            name='currency_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_currency_account', to='currency_rates.currencyaccount'),
        ),
    ]
