# Generated by Django 4.2.6 on 2023-12-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
