# Generated by Django 4.2.6 on 2023-12-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rates', '0003_alter_currencyaccount_balance'),
        ('credit', '0003_alter_credit_unique_together_credit_currency_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='currency_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_currency_account', to='currency_rates.currencyaccount'),
        ),
    ]
