# Generated by Django 4.2.6 on 2023-12-10 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('KZT', 'KZT'), ('EUR', 'EUR'), ('PLN', 'PLN'), ('UAH', 'UAH'), ('TRY', 'TRY'), ('INR', 'INR'), ('BYN', 'BYN'), ('ZAR', 'ZAR'), ('XOF', 'XOF'), ('VND', 'VND'), ('TWD', 'TWD'), ('TND', 'TND'), ('THB', 'THB'), ('SGD', 'SGD'), ('SEK', 'SEK'), ('SAR', 'SAR'), ('QAR', 'QAR'), ('PKR', 'PKR'), ('PHP', 'PHP'), ('OMR', 'OMR'), ('NZD', 'NZD'), ('NOK', 'NOK'), ('NGN', 'NGN'), ('MYR', 'MYR'), ('MXN', 'MXN'), ('MUR', 'MUR'), ('MAD', 'MAD'), ('LYD', 'LYD'), ('LKR', 'LKR'), ('KWD', 'KWD'), ('KRW', 'KRW'), ('JPY', 'JPY'), ('JOD', 'JOD'), ('ISK', 'ISK'), ('ILS', 'ILS'), ('IDR', 'IDR'), ('HUF', 'HUF'), ('HKD', 'HKD'), ('GBP', 'GBP'), ('ETB', 'ETB'), ('EGP', 'EGP'), ('DZD', 'DZD'), ('DKK', 'DKK'), ('CZK', 'CZK'), ('CNY', 'CNY'), ('CLP', 'CLP'), ('CHF', 'CHF'), ('CAD', 'CAD'), ('BRL', 'BRL'), ('BHD', 'BHD'), ('BGN', 'BGN'), ('BDT', 'BDT'), ('AUD', 'AUD'), ('ARS', 'ARS'), ('AOA', 'AOA'), ('AMD', 'AMD'), ('BYR', 'BYR'), ('AED', 'AED'), ('COP', 'COP'), ('RON', 'RON'), ('PEN', 'PEN'), ('USDT', 'USDT')], max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description of permission')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255, verbose_name='Description of role')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='RolesPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_system.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_system.role')),
            ],
            options={
                'verbose_name': 'RolesPermissions',
                'verbose_name_plural': 'RolesPermissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('secret_code', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='secret code')),
                ('secret_code_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of secret code update')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account_system.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of money')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_system.currency')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'unique_together': {('owner', 'currency')},
            },
        ),
    ]
