# Generated by Django 4.2.6 on 2023-12-06 20:46

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of $')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description of permission')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255, verbose_name='Description of role')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=13)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcode/')),
                ('otp_code', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='OTP code')),
                ('otp_code_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of otp code update')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account_system.account')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account_system.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='RolesPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_system.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_system.role')),
            ],
            options={
                'verbose_name': 'RolesPermissions',
                'verbose_name_plural': 'RolesPermissions',
            },
        ),
    ]
