# Generated by Django 4.2.6 on 2023-12-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_system', '0002_remove_user_otp_code_remove_user_otp_code_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
