# Generated by Django 4.2.6 on 2023-12-09 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_system', '0004_remove_user_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('KZT', 'KZT'), ('EUR', 'EUR'), ('PLN', 'PLN'), ('UAH', 'UAH'), ('TRY', 'TRY'), ('INR', 'INR'), ('BYN', 'BYN'), ('ZAR', 'ZAR'), ('XOF', 'XOF'), ('VND', 'VND'), ('TWD', 'TWD'), ('TND', 'TND'), ('THB', 'THB'), ('SGD', 'SGD'), ('SEK', 'SEK'), ('SAR', 'SAR'), ('QAR', 'QAR'), ('PKR', 'PKR'), ('PHP', 'PHP'), ('OMR', 'OMR'), ('NZD', 'NZD'), ('NOK', 'NOK'), ('NGN', 'NGN'), ('MYR', 'MYR'), ('MXN', 'MXN'), ('MUR', 'MUR'), ('MAD', 'MAD'), ('LYD', 'LYD'), ('LKR', 'LKR'), ('KWD', 'KWD'), ('KRW', 'KRW'), ('JPY', 'JPY'), ('JOD', 'JOD'), ('ISK', 'ISK'), ('ILS', 'ILS'), ('IDR', 'IDR'), ('HUF', 'HUF'), ('HKD', 'HKD'), ('GBP', 'GBP'), ('ETB', 'ETB'), ('EGP', 'EGP'), ('DZD', 'DZD'), ('DKK', 'DKK'), ('CZK', 'CZK'), ('CNY', 'CNY'), ('CLP', 'CLP'), ('CHF', 'CHF'), ('CAD', 'CAD'), ('BRL', 'BRL'), ('BHD', 'BHD'), ('BGN', 'BGN'), ('BDT', 'BDT'), ('AUD', 'AUD'), ('ARS', 'ARS'), ('AOA', 'AOA'), ('AMD', 'AMD'), ('BYR', 'BYR'), ('AED', 'AED'), ('COP', 'COP'), ('RON', 'RON'), ('PEN', 'PEN'), ('USDT', 'USDT')], primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to='account_system.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_system.currency'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('owner', 'currency')},
        ),
    ]
