# Generated by Django 4.2.6 on 2023-12-09 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_system', '0005_currency_account_owner_account_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_id',
        ),
    ]
