# Generated by Django 4.2.6 on 2023-12-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(choices=[('AAPL', 'AAPL'), ('TSLA', 'TSLA'), ('AMZN', 'AMZN'), ('META', 'META'), ('GOOG', 'GOOG')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockprices'),
        ),
    ]
