# Generated by Django 4.0.6 on 2023-12-10 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='inv_portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_inv_port', to='stocks.investmentportfolio'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='stock_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stockprices'),
        ),
        migrations.AddField(
            model_name='stockprices',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='investmentstrategy',
            name='investment_portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stocks.investmentportfolio'),
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='investmentportfolio',
            unique_together={('owner', 'name')},
        ),
    ]
