# Generated by Django 4.2.6 on 2023-12-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_name_alter_stocktransaction_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprices',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
    ]
