# Generated by Django 4.0.6 on 2023-12-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('KZT', 'KZT'), ('EUR', 'EUR'), ('PLN', 'PLN'), ('UAH', 'UAH'), ('TRY', 'TRY'), ('INR', 'INR'), ('BYN', 'BYN'), ('ZAR', 'ZAR'), ('XOF', 'XOF'), ('VND', 'VND'), ('TWD', 'TWD'), ('TND', 'TND'), ('THB', 'THB'), ('SGD', 'SGD'), ('SEK', 'SEK'), ('SAR', 'SAR'), ('QAR', 'QAR'), ('PKR', 'PKR'), ('PHP', 'PHP'), ('OMR', 'OMR'), ('NZD', 'NZD'), ('NOK', 'NOK'), ('NGN', 'NGN'), ('MYR', 'MYR'), ('MXN', 'MXN'), ('MUR', 'MUR'), ('MAD', 'MAD'), ('LYD', 'LYD'), ('LKR', 'LKR'), ('KWD', 'KWD'), ('KRW', 'KRW'), ('JPY', 'JPY'), ('JOD', 'JOD'), ('ISK', 'ISK'), ('ILS', 'ILS'), ('IDR', 'IDR'), ('HUF', 'HUF'), ('HKD', 'HKD'), ('GBP', 'GBP'), ('ETB', 'ETB'), ('EGP', 'EGP'), ('DZD', 'DZD'), ('DKK', 'DKK'), ('CZK', 'CZK'), ('CNY', 'CNY'), ('CLP', 'CLP'), ('CHF', 'CHF'), ('CAD', 'CAD'), ('BRL', 'BRL'), ('BHD', 'BHD'), ('BGN', 'BGN'), ('BDT', 'BDT'), ('AUD', 'AUD'), ('ARS', 'ARS'), ('AOA', 'AOA'), ('AMD', 'AMD'), ('BYR', 'BYR'), ('AED', 'AED'), ('COP', 'COP'), ('RON', 'RON'), ('PEN', 'PEN'), ('USDT', 'USDT')], help_text='Currency name from ALL_CURRENCIES list', max_length=4, primary_key=True, serialize=False, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Currency Account',
                'verbose_name_plural': 'Currency Accounts',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('date_of_use', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Currency rate',
                'verbose_name_plural': 'Currency rates',
            },
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('currency_rate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency_rates.currencyrate')),
            ],
            options={
                'verbose_name': 'Currency Transaction',
                'verbose_name_plural': 'Currency Transactions',
            },
        ),
    ]
