# Generated by Django 4.0.6 on 2023-12-10 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency_rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currencytransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_rates.currency'),
        ),
        migrations.AddField(
            model_name='currencyaccount',
            name='currency',
            field=models.ForeignKey(default='USDT', on_delete=django.db.models.deletion.SET_DEFAULT, to='currency_rates.currency'),
        ),
        migrations.AddField(
            model_name='currencyaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='currencyaccount',
            unique_together={('currency', 'user')},
        ),
    ]
