# Generated by Django 4.2.6 on 2023-12-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyaccount',
            name='currency',
            field=models.ForeignKey(default='USDT', on_delete=django.db.models.deletion.SET_DEFAULT, to='currency_rates.currency'),
        ),
    ]
