# Generated by Django 4.2.6 on 2023-12-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rates', '0002_alter_currencyaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
