# Generated by Django 4.2.6 on 2023-12-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_rates', '0002_alter_currencyaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='rate',
            field=models.FloatField(),
        ),
    ]
