CURRENCY_CODE_USD = 'USD'
CURRENCY_CODE_RUB = 'RUB'
CURRENCY_CODE_KZT = 'KZT'
CURRENCY_CODE_EUR = 'EUR'
CURRENCY_CODE_PLN = 'PLN'
CURRENCY_CODE_UAH = 'UAH'
CURRENCY_CODE_TRY = 'TRY'
CURRENCY_CODE_INR = 'INR'
CURRENCY_CODE_BYN = 'BYN'

CURRENCY_CODE_ZAR = 'ZAR'
CURRENCY_CODE_XOF = 'XOF'
CURRENCY_CODE_VND = 'VND'
CURRENCY_CODE_TWD = 'TWD'
CURRENCY_CODE_TND = 'TND'
CURRENCY_CODE_THB = 'THB'
CURRENCY_CODE_SGD = 'SGD'
CURRENCY_CODE_SEK = 'SEK'
CURRENCY_CODE_SAR = 'SAR'
CURRENCY_CODE_QAR = 'QAR'
CURRENCY_CODE_PKR = 'PKR'
CURRENCY_CODE_PHP = 'PHP'
CURRENCY_CODE_OMR = 'OMR'
CURRENCY_CODE_NZD = 'NZD'
CURRENCY_CODE_NOK = 'NOK'
CURRENCY_CODE_NGN = 'NGN'
CURRENCY_CODE_MYR = 'MYR'
CURRENCY_CODE_MXN = 'MXN'
CURRENCY_CODE_MUR = 'MUR'
CURRENCY_CODE_MAD = 'MAD'
CURRENCY_CODE_LYD = 'LYD'
CURRENCY_CODE_LKR = 'LKR'
CURRENCY_CODE_KWD = 'KWD'
CURRENCY_CODE_KRW = 'KRW'
CURRENCY_CODE_JPY = 'JPY'
CURRENCY_CODE_JOD = 'JOD'
CURRENCY_CODE_ISK = 'ISK'
CURRENCY_CODE_ILS = 'ILS'
CURRENCY_CODE_IDR = 'IDR'
CURRENCY_CODE_HUF = 'HUF'
CURRENCY_CODE_HKD = 'HKD'
CURRENCY_CODE_GBP = 'GBP'
CURRENCY_CODE_ETB = 'ETB'
CURRENCY_CODE_EGP = 'EGP'
CURRENCY_CODE_DZD = 'DZD'
CURRENCY_CODE_DKK = 'DKK'
CURRENCY_CODE_CZK = 'CZK'
CURRENCY_CODE_CNY = 'CNY'
CURRENCY_CODE_CLP = 'CLP'
CURRENCY_CODE_CHF = 'CHF'
CURRENCY_CODE_CAD = 'CAD'
CURRENCY_CODE_BRL = 'BRL'
CURRENCY_CODE_BHD = 'BHD'
CURRENCY_CODE_BGN = 'BGN'
CURRENCY_CODE_BDT = 'BDT'
CURRENCY_CODE_AUD = 'AUD'
CURRENCY_CODE_ARS = 'ARS'
CURRENCY_CODE_AOA = 'AOA'
CURRENCY_CODE_AMD = 'AMD'
CURRENCY_CODE_PEN = 'PEN'
CURRENCY_CODE_COP = 'COP'
CURRENCY_CODE_RON = 'RON'


CURRENCY_CODE_BYR = 'BYR'
CURRENCY_CODE_AED = 'AED'

CURRENCY_CODE_USDT = 'USDT'


ALL_CURRENCY_CODES = (
    CURRENCY_CODE_USD,
    CURRENCY_CODE_RUB,
    CURRENCY_CODE_KZT,
    CURRENCY_CODE_EUR,
    CURRENCY_CODE_PLN,
    CURRENCY_CODE_UAH,
    CURRENCY_CODE_TRY,
    CURRENCY_CODE_INR,
    CURRENCY_CODE_BYN,
    CURRENCY_CODE_ZAR,
    CURRENCY_CODE_XOF,
    CURRENCY_CODE_VND,
    CURRENCY_CODE_TWD,
    CURRENCY_CODE_TND,
    CURRENCY_CODE_THB,
    CURRENCY_CODE_SGD,
    CURRENCY_CODE_SEK,
    CURRENCY_CODE_SAR,
    CURRENCY_CODE_QAR,
    CURRENCY_CODE_PKR,
    CURRENCY_CODE_PHP,
    CURRENCY_CODE_OMR,
    CURRENCY_CODE_NZD,
    CURRENCY_CODE_NOK,
    CURRENCY_CODE_NGN,
    CURRENCY_CODE_MYR,
    CURRENCY_CODE_MXN,
    CURRENCY_CODE_MUR,
    CURRENCY_CODE_MAD,
    CURRENCY_CODE_LYD,
    CURRENCY_CODE_LKR,
    CURRENCY_CODE_KWD,
    CURRENCY_CODE_KRW,
    CURRENCY_CODE_JPY,
    CURRENCY_CODE_JOD,
    CURRENCY_CODE_ISK,
    CURRENCY_CODE_ILS,
    CURRENCY_CODE_IDR,
    CURRENCY_CODE_HUF,
    CURRENCY_CODE_HKD,
    CURRENCY_CODE_GBP,
    CURRENCY_CODE_ETB,
    CURRENCY_CODE_EGP,
    CURRENCY_CODE_DZD,
    CURRENCY_CODE_DKK,
    CURRENCY_CODE_CZK,
    CURRENCY_CODE_CNY,
    CURRENCY_CODE_CLP,
    CURRENCY_CODE_CHF,
    CURRENCY_CODE_CAD,
    CURRENCY_CODE_BRL,
    CURRENCY_CODE_BHD,
    CURRENCY_CODE_BGN,
    CURRENCY_CODE_BDT,
    CURRENCY_CODE_AUD,
    CURRENCY_CODE_ARS,
    CURRENCY_CODE_AOA,
    CURRENCY_CODE_AMD,
    CURRENCY_CODE_BYR,
    CURRENCY_CODE_AED,
    CURRENCY_CODE_COP,
    CURRENCY_CODE_RON,
    CURRENCY_CODE_PEN,
    CURRENCY_CODE_USDT,
)

ALL_CURRENCY_CODES_CHOICES = [
    (code, code)
    for code in ALL_CURRENCY_CODES
]
