APPLE_STOCK_CODE = 'AAPL'
TESLA_STOCK_CODE = 'TSLA'
AMAZON_STOCK_CODE = 'AMZN'
META_STOCK_CODE = 'META'
MICROSOFT_STOCK_CODE = 'MSFT'
GOOGLE_STOCK_CODE = 'GOOG'

ALL_STOCK_CODES = (
    APPLE_STOCK_CODE,
    TESLA_STOCK_CODE,
    AMAZON_STOCK_CODE,
    META_STOCK_CODE,
    GOOGLE_STOCK_CODE,
)

ALL_STOCK_CHOICES = (
    (code, code)
    for code in ALL_STOCK_CODES
)
