# Generated by Django 4.0.6 on 2023-12-10 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remittance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='receiver',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remittance',
            name='sender',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
