# Generated by Django 4.2.6 on 2023-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='commission',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='count',
            field=models.FloatField(),
        ),
    ]
