# Generated by Django 4.2.6 on 2023-12-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0002_alter_remittance_commission_alter_remittance_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
