# Generated by Django 4.2.6 on 2023-12-10 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_system', '0009_alter_account_amount'),
        ('transaction_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Commission'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account_system.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of money'),
        ),
    ]
