# Generated by Django 4.2.6 on 2023-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_system', '0003_alter_transaction_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='min amount of money')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='%')),
            ],
            options={
                'verbose_name': 'LoyaltyConfig',
                'verbose_name_plural': 'LoyaltyConfigs',
            },
        ),
    ]
