# Generated by Django 4.2.6 on 2023-12-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_system', '0004_loyaltyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyconfig',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='%'),
        ),
    ]
