# Generated by Django 4.2.6 on 2023-12-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_system', '0005_loyaltyconfig_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyconfig',
            name='commission',
        ),
    ]
