# Generated by Django 4.2.6 on 2023-11-27 15:47

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=13)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcode/')),
                ('otp_code', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='OTP code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of update')),
                ('otp_code_updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of otp code update')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
