# Generated by Django 4.2.6 on 2023-12-06 20:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_interest', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='The interest rate of the credit')),
            ],
            options={
                'verbose_name': 'GeneralConfig',
                'verbose_name_plural': 'GeneralConfigs',
            },
        ),
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount of $')),
                ('period', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Amount of years')),
                ('request_timestamp', models.DateTimeField(auto_now=True, verbose_name='Application date')),
                ('approved', models.BooleanField(blank=True, verbose_name='Approved')),
                ('approved_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='The date of issuing approval of the application')),
                ('closed_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='The date of issuing approval of the application')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='account_system.account')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditRequests', to='account_system.user')),
            ],
            options={
                'verbose_name': 'CreditRequest',
                'verbose_name_plural': 'CreditRequests',
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='The amount for payment')),
                ('payment_timestamp', models.DateTimeField(verbose_name='Payment date')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditPayments', to='credit_system.creditrequest')),
            ],
            options={
                'verbose_name': 'CreditPayment',
                'verbose_name_plural': 'CreditPayments',
            },
        ),
    ]
