# Generated by Django 4.2.6 on 2023-12-09 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_system', '0005_currency_account_owner_account_currency_and_more'),
        ('credit_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('name', models.CharField()),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account_system.currency')),
            ],
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='creditrequest',
            name='manager_id',
        ),
        migrations.DeleteModel(
            name='GeneralConfig',
        ),
        migrations.RemoveField(
            model_name='creditpayment',
            name='request_id',
        ),
        migrations.DeleteModel(
            name='CreditRequest',
        ),
        migrations.AddField(
            model_name='credit',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_configuration', to='credit_system.creditconfiguration'),
        ),
        migrations.AddField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit', to='account_system.user'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='credit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_payment_credit', to='credit_system.credit'),
        ),
    ]
